Decouple Shared Components
panther-labs/panther_analysis_tool pull request #183
Opened 2022-05-06 17:11 UTC by wey-chiang

### Background

The Detections Engine Backend in Panther has shared dependencies with PAT. This PR removes the shared code and updates PAT to depend on the new `panther-core` library.

### Changes

* Deleted shared code
* Updated references to point to `panther-core`

### Testing

* `make ci`

2022-05-06 17:12 UTC, darwayne approved these changes
🧬 LGTM🧬

2022-05-06 17:20 UTC, nmartin413 commented
`util.py` had some boto stuff that shouldn't be in `panther_core` - the concept was to keep all networking/remote interactions and clients in `panther_core`'s consumers.

2022-05-06 17:23 UTC, wey-chiang commented
> `util.py` had some boto stuff that shouldn't be in `panther_core` - the concept was to keep all networking/remote interactions and clients in `panther_core`'s consumers.

Good callout -- we define our own `get_client` in the detections engine so I'll remove that from `panther-core` and add it back here

2022-05-06 17:28 UTC, danbiwer approved these changes

2022-05-06 17:29 UTC, nmartin413 commented
@wey-chiang I already removed it in my py exec models ++

2022-05-06 17:31 UTC, wey-chiang commented
> @wey-chiang I already removed it in my py exec models ++

Looks like one of my commits reverted those changes heh... it's been removed

2022-05-06 17:33 UTC, darwayne submitted a review, later dismissed

2022-05-06 17:42 UTC, wey-chiang commented
We should hold off on merging and cutting a new release until all the PRs for `panther-analysis` and `panther-enterprise` are ready to go

2022-05-06 17:43 UTC, wey-chiang commented
Also including changes for a major version bump in this PR so we're ready to get a release out once this is merged

2022-05-06 18:34 UTC, lindsey-w commented on panther_analysis_tool/main.py
> +    parser.add_argument("--version", action="version", version="panther_analysis_tool 1.0.0")
should we remove the version bump until we are ready to cut a release?

2022-05-06 18:34 UTC, lindsey-w commented on setup.py
>      install_requires=install_requires,
do we need to add `panther_core` to the `install_requires` list?

2022-05-13 14:32 UTC, wey-chiang reviewed
lazy version bump

2022-05-31 17:28 UTC, lindsey-w requested changes
will be scheduling a meeting about deps management

2022-07-27 20:59 UTC, closed without merging